// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = 'https://mtmdwmvxgxtbcyeuwomr.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im10bWR3bXZ4Z3h0YmN5ZXV3b21yIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjYxNzQzOTEsImV4cCI6MjA4MTc1MDM5MX0.tvTf4NpDRzYzM7lF6KPXn5zyBfDtkoGqTu9FLxoWzlo';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    }
  }
);
