// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = 'https://lliuchxuispxpgwubfdw.supabase.co';
const SUPABASE_PUBLISHABLE_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxsaXVjaHh1aXNweHBnd3ViZmR3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjYxNzAxMDgsImV4cCI6MjA4MTc0NjEwOH0.IjChzUyu727KAJTduyGS03I1ujLSe2K9S2-GEn82YOo';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    }
  }
);
